### Dynamic Programming

#### Properties:  
- **Overlapping subproblem:** Solutions of subproblems can be used to calculate the final solution.  
**Example**: Fibonacci(2) = Fibonacci(1) + Fibonnaci(0).  
- **Optimal sub structure:** If optimal solution of a problem can be obtained using optimal solutions of its subproblems.  
**Example**: If y is in the shortest path from x to z, then shortest_path(x,z) = shortest_path(x,y)+shortest_path(y,z).  
**Negative example**: Longest path doesnot have optimal substructure. For a square ABCD, longest path from A to C is not sum of longest paths from A to B and B to c.  

#### 2 Ways of storing values:  
- **Memoization (top down):** create a lookup table with all NULL values. For every sub problem, lookup if it has a value. If the value is NULL, calculate it, else just use it.  
- **Tabulation (bottom up):** Start from the smallest sub problem and calculating all the values building up.  
- Memoization doesn't need to calculate and store values of all sub problems.  

#### Advantage over Recursion: Recursion doesnot reuse the previously calculated values.  

In [4]:
# Example with Fibonacci
def fib_memoization(n, lookup):
    if n<=1:
        lookup[n] = n
    if lookup[n]==None:
        lookup[n] = fib(n-1, lookup)+ fib(n-2, lookup)
    return lookup[n]

def fib_tabulation(n):
    lookup = [0]*(n+1)
    lookup[1] = 1
    for i in range(2, n+1):
        lookup[i] = lookup[i-1] + lookup[i-2]
    return lookup[-1]

n = 20
lookup = [None]*50
print('Using memoization: ', fib_memoization(n, lookup))
print('Using tabulation: ', fib_tabulation(n))

Using memoization:  6765
Using tabulation:  6765


In [12]:
# Problem 1: Longest Increasing subsequence
# input = {10, 22, 9, 33, 21, 50, 41, 60, 80}
# LIS = {10, 22, 33, 50, 60, 80}
# output = 6
# complexity = O(n^2) (n for recursion, n for finding max)
import numpy as np

# def LIS(seq, lookup):
#     n = len(seq)
#     if(n==0 or n==1):
#         lookup[n] = n
#     if lookup[n]==None:
#         if seq[-2]>=seq[-1]:
#             lookup[n] = LIS(seq[:-1], lookup)
#         else:
#             lookup[n] = max(LIS(seq[:-1], lookup)+1, LIS(seq[:-2], lookup))
#     return lookup[n]
def LIS(seq, lookup):
    n = len(seq)
    if(n==0 or n==1):
        lookup[n] = n
    if lookup[n]==None:
        if seq[-2]>=seq[-1]:
            x = max(LIS(seq[:-2], lookup)+1, x)
        else:
        
        lookup[n] = max(LIS(seq[:-1], lookup), x)
        
        if seq[-2]>=seq[-1]:
            lookup[n] = LIS(seq[:-1], lookup)
        else:
            lookup[n] = max(LIS(seq[:-1], lookup)+1, LIS(seq[:-2], lookup))
    return lookup[n]

#seq = [10, 22, 9, 33, 21, 50, 41, 60, 80]
seq = [4,10,4,3,8,9]
lookup = [None]*(len(seq)+1)
print(LIS(seq, lookup))

4


In [19]:
# Problem 2: Longest common subsequence
# input: “ABCDGH”, “AEDFHR”
# LCS: “ADH”
# output: 3
# complexity: O(mn)
import numpy as np

def LCS(a1, a2):
    if(len(a1)==0 or len(a2)==0):
        lcs = 0
    else:
        # If last letters are same, LCS = 1 + LCS(arrays removing last letter)
        if a1[-1]==a2[-1]:
            lcs = LCS(a1[:-1], a2[:-1]) + 1
        # else, LCS = max(remove last letter of either arrays)
        else:
            lcs = np.max((LCS(a1[:-1], a2), LCS(a1, a2[:-1])))
    return lcs

a1 = 'ABCDGH'
a2 = 'AEDFHR'
print(LCS(a1,a2))

3


In [15]:
# Problem 3: Edit Distance
# input: str1 = 'sunday', str2 = 'saturday'
# output: convert str1 to str2 using min operations
# of insert, delete, replace
import numpy as np

def edit_dist(str1, str2, m, n):
    dp = np.zeros((m+1,n+1))
    for i in range(m+1):
        for j in range(n+1):
            if i==0:
                dp[i,j] = j
            elif j==0:
                dp[i,j] = i
            elif str1[i-1]==str2[j-1]:
                dp[i,j] = dp[i-1, j-1]
            else:
                dp[i, j] = 1+min(dp[i-1,j], dp[i,j-1], dp[i-1,j-1])
    return dp[m,n]                                        
    
str1 = 'sunday'
str2 = 'saturday'
print(edit_dist(str1, str2, len(str1), len(str2)))

3.0


In [20]:
# Problem 4: Min Cost Path 
def min_cost_path(cost, x, y, lookup):
    if(x==-1 or y==-1):
        return 100
    if lookup[x,y]==-1:    
        lookup[x,y] = cost[x,y]+ min(min_cost_path(cost, x-1, y, lookup),
                          min_cost_path(cost, x, y-1, lookup), 
                          min_cost_path(cost, x-1, y-1, lookup))
    return lookup[x,y]

cost_table = np.array(([1,2,3],
                       [4,8,2],
                      [1,5,3]))
lookup_table = np.zeros_like(cost_table)-1
lookup_table[0,0] = cost_table[0,0]
x=2; y=2
print(min_cost_path(cost_table, x, y, lookup_table))

8


In [28]:
# Problem 5: Coin change
import numpy as np

def count(S, m, n):
    # Lookup table
    # For table[i,j], n=i and S=S[:j]
    table = np.zeros((n+1, m))
    # Initialize for n=0
    table[0,:] = 1
    for i in range(1, n+1):
        for j in range(m):
            # Include S[j] 
            x = table[i-S[j], j] if i-S[j]>=0 else 0
            # Exclude S[j]
            y = table[i, j-1] if j>=1 else 0
            # Total
            table[i,j] = x+y
    return table[n,m-1]

n = 4
S = [1,2,3]
m = len(S)
print(count(S, m, n))

4.0


In [19]:
# Matrix Multiplication
import numpy as np
MAX_VAL = np.iinfo(np.int64).max

def matmult_ops(a):
    N = len(a)
    lut = np.zeros((N-1, N-1)).astype(int)
    for c in range(1, N-1):
        for r in range(c-1, -1, -1):
            minops = MAX_VAL
            for i in range(r, c):
                x = lut[r,i] + lut[i+1,c]
                y = a[r]*a[i+1]*a[c+1]
                minops = min(minops, x+y)
            lut[r,c] = minops
    return lut[0,N-2]

#a = [4, 2, 3, 1, 3]
a = [10, 20, 30, 40, 30]
print(matmult_ops(a))

30000


In [4]:
import numpy as np
a = np.zeros((3,3)).astype(int)
print(np.iinfo(np.int64).max)

9223372036854775807


In [16]:
# Knapsack Problem
import numpy as np

def maxval(wt, val, W, lookup):
    if sum(wt)<=W:
        if lookup[len(wt)-1] == -1:
            lookup[len(wt)-1] = sum(wt)
        return lookup[len(wt)-1]
    if len(wt)==1:
        return 0
    return max(maxval(wt[:-1], val[:-1], W, lookup), 
               maxval(wt[:-1], val[:-1], W-wt[-1], lookup)+val[-1])

wt = [10,20,30]
val = [60,100,120]
W = 50
# Lookup to store sum of all weights in the list
# Initialize all values to -1, except the 1st (to 0)

lookup = np.zeros((len(wt)))
lookup[1:] = -1
print(maxval(wt, val, W, lookup))

220


In [31]:
# Egg dropping problem
import numpy as np

def minTrials(N, K):
    lut = np.zeros((N,K+1))
    for i in range(K+1):
        lut[0,i] = i
    for i in range(1, N):
        lut[i,0] = 0
        lut[i,1] = 1
    for n in range(1, N):
        for k in range(2, K+1):
            for x in range(1, k+1):
                val = max(lut[n-1, x-1], lut[n, k-x])+1
                if x==1:
                    lut[n,k] = val
                else:
                    lut[n,k] = min(val, lut[n,k])
    return lut[N-1,K]

n = 2
k = 36
print(minTrials(n, k))

8.0


In [56]:
# Longest Increasing Subsequence
import numpy as np

def LIS(a, l, r, lut):
    if lut[l,r]==-1:
        if(l==r-1 and a[l]==a[r]):
            lut[l, r] = 2
        elif l==r:
            lut[l, r] = 1
        elif l>r:
            lut[l, r] = 0
        else:
            x = LIS(a, l, r-1, lut)
            flag=0
            for i, char in enumerate(a[l:r]):
                if char==a[r]:
                    flag=1
                    break
            y1 = LIS(a, l+i+1, r, lut)
            if flag==1:
                y2 = LIS(a, l+i+1, r-1, lut) + 2
            else:
                y2 = 0
            lut[l, r] = max(x, y1, y2)           
    return lut[l, r]
    
#a = 'bbabcbcab'
#a = 'geeksforgeeks'
a = 'ab'
N = len(a)
lut = np.zeros((N,N))-1
print(LIS(a, 0, N-1, lut))

1.0


In [61]:
# Longest Increasing Subsequence
import numpy as np

def LIS(a, l, r, lut):
    if lut[l,r]==-1:
        if(l==r-1 and a[l]==a[r]):
            lut[l, r] = 2
        elif l==r:
            lut[l, r] = 1
        elif l>r:
            lut[l, r] = 0
        else:
            x = LIS(a, l, r-1, lut)
            if a[l]!=a[r]:
                y = LIS(a, l+1, r, lut)
            else:
                y = LIS(a, l+1, r-1, lut) + 2
            lut[l, r] = max(x, y)         
    return lut[l, r]
    
#a = 'bbabcbcab'
#a = 'geeksforgeeks'
a = 'cbb'
N = len(a)
lut = np.zeros((N,N))-1
print(LIS(a, 0, N-1, lut))

2.0


In [6]:
# Cutting a rod
import numpy as np
def maxval(vals):
    N = len(vals)
    lut = np.zeros((N+1,N+1))
    for i in range(1, N+1):
        for j in range(1, N+1):
            lut[i,j] = max(lut[i,j-1], lut[i-j,i-j] + vals[j-1])
    print(lut)
    return lut[N, N]

vals = [1, 5, 8, 9, 10, 17, 17, 20]
print(maxval(vals))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  5.  8.  9. 10. 17. 17. 20.]
 [ 0.  2.  5.  8.  9. 10. 17. 17. 20.]
 [ 0.  6.  6.  8.  9. 10. 17. 17. 20.]
 [ 0.  9. 10. 10. 10. 10. 17. 17. 20.]
 [ 0. 11. 13. 13. 13. 13. 17. 17. 20.]
 [ 0. 14. 15. 16. 16. 16. 17. 17. 20.]
 [ 0. 18. 18. 18. 18. 18. 18. 18. 20.]
 [ 0. 19. 22. 22. 22. 22. 22. 22. 22.]]
22.0
