# Sorting


In [2]:
import numpy as np
from time import time

## 1. Merge Sort

- Divide and Conquer Algorithm  
- **Complexity** = $2T(n/2) + \theta(n) = \theta(n\log n)$  
- **Auxiliary Space** = O(N) extra space required  
- **When to use** - Merge Sort is useful for sorting linked lists in O(nLogn) time.In case of linked lists the case is different mainly due to difference in memory allocation of arrays and linked lists. Unlike arrays, linked list nodes may not be adjacent in memory. Unlike array, in linked list, we can insert items in the middle in O(1) extra space and O(1) time. Therefore merge operation of merge sort can be implemented without extra space for linked lists. Unlike arrays, we can not do random access in linked list. Quick Sort requires a lot of this kind of access.  
- **When not to use** -  When dealing with arrays as quick sort is more advantageous then.  
```
merge: merges arr[l:m] and arr[m+1:r]
MergeSort(arr[], l,  r)
If r > l
     1. Find the middle point to divide the array into two halves:  
             middle m = (l+r)/2
     2. Call mergeSort for first half:   
             Call mergeSort(arr, l, m)
     3. Call mergeSort for second half:
             Call mergeSort(arr, m+1, r)
     4. Merge the two halves sorted in step 2 and 3:
             Call merge(arr, l, m, r)
```

In [50]:
# Merge Sort
def merge(arr, l, m, r):
    L = arr[l:m+1].copy()
    R = arr[m+1:r+1].copy()
    i = 0; j = 0; k = l
    while(i<m-l+1 and j<r-m):
        if L[i]<R[j]:
            arr[k] = L[i]; i += 1
        else:
            arr[k] = R[j]; j += 1
        k += 1
    if i<m-l+1:
        arr[k:r+1] = L[i:]
    if j<r-m:
        arr[k:r] = R[j:]

def mergeSort(arr, l, r):
    if r>l:
        m = np.floor(0.5*(l+r)).astype(int)
        mergeSort(arr, l, m)
        mergeSort(arr, m+1, r)
        merge(arr, l, m, r)

arr = np.array(([38, 27, 43, 3, 9, 82, 10]))
print('Array: ', arr)
t=time()
mergeSort(arr, 0, len(arr)-1)
print('Sorted Array: ',arr)
print('Time taken = ',time()-t,' sec')

Array:  [38 27 43  3  9 82 10]
Sorted Array:  [ 3  9 10 27 38 43 82]
Time taken =  0.0012962818145751953  sec


## 2. Quick Sort

- Divide and Conquer algorithm  
- Any element can be pivot (CLRS: last element)  
- Keep pivot in correct location in sorted array
- **Complexity** :
    - Worst case: Array is already sorted. $T(n) = T(n-1) + \theta(n) = \theta(n^2)$  
    - Best case : Pivot is always middle element. $T(n) = 2T(n/2) + \theta(n) = \theta(n\log n)$  
- Auxiliary space: No extra space needed. In-place sorting.  
- 3 way quicksort: 3 splits: arr with smaller elts, array with equal elts, array with larger elts.  
- Further: Tail call optimization  
- **When to use** :
    - With arrays. It is in-place sort and has no extra space unlike merge sort (O(N)).  
    - The randomized version has expected time complexity of O(nLogn). This works well in practice.  
    - Cache friendly sorting algorithm as it has good locality of reference when used for arrays.  
    - Its tail recursive, therefore tail call optimizations is done
- **When not to use** - When sorting linked lists as the elements can only be accessed sequentially. Use merge sort here.  

```
/* low  --> Starting index,  high  --> Ending index */
partition: This function takes last element as pivot, places the pivot element at its correct position in sorted array, and places all smaller (smaller than pivot) to left of pivot and all greater elements to right of pivot
quickSort(arr[], low, high){
    if (low < high){
        /* pi is partitioning index, arr[pi] is now
           at right place */
        pi = partition(arr, low, high);

        quickSort(arr, low, pi - 1);  // Before pi
        quickSort(arr, pi + 1, high); // After pi
    }
}
```

In [14]:
# Quick Sort
def partition(arr, low, high):
    pivot_index = low
    for i in range(low, high):
        if arr[i] < arr[high]:
            arr[i], arr[pivot_index] = arr[pivot_index], arr[i]
            pivot_index += 1
    arr[pivot_index], arr[high] = arr[high], arr[pivot_index]
    return pivot_index

def quickSort(arr, low, high):
    if low<high:
        pivot_index = partition(arr, low, high)
        print('low = ',low, ' high = ',high, arr)
        quickSort(arr, low, pivot_index-1)
        quickSort(arr, pivot_index+1, high)

arr = np.array(([38, 27, 43, 3, 9, 82, 10]))
print('Array: ', arr)
t=time()
quickSort(arr, 0, len(arr)-1)
print('Sorted Array: ',arr)
print('Time taken = ',time()-t,' sec')

Array:  [38 27 43  3  9 82 10]
low =  0  high =  6 [ 3  9 10 38 27 82 43]
low =  0  high =  1 [ 3  9 10 38 27 82 43]
low =  3  high =  6 [ 3  9 10 38 27 43 82]
low =  3  high =  4 [ 3  9 10 27 38 43 82]
Sorted Array:  [ 3  9 10 27 38 43 82]
Time taken =  0.0028710365295410156  sec


## 3. Radix Sort

1. Comparison based algos (merge, quick etc) best complexity is O(nlogn).  
2. Radix can do O(n+k) if all elements $\in [1,k]$.  
3. Sorts 1s place digits, then 10s place digits, and so on using counting sort.  
4. Counting Sort:  
    - Find cummulative frequency (CF) of all unique numbers.  
    - Iterate from last element to first. Keep each element in its CF value index in sorted array and decrease the CF value by 1.   
    - Complexity= O(n+k), auxiliary space = O(n+k). k = largest element.  
5. Complexity: 
    - Radix Sort takes O(d*(n+b)) time (b: base of numbers for ex 10, d: max number of digits, d=O(logb(max_value))).   
    - Overall time complexity is O((n+b) * logb(k)).  
    - For k <= nc where c is a constant and b=n, we get the time complexity as O(n). 
6. Disadvantages compared to quick sort: 
    - The constant factors hidden in asymptotic notation are higher for Radix Sort. 
    - Quick-Sort uses hardware caches more effectively.  
    - Radix sort uses counting sort as a subroutine and counting sort takes extra space to sort numbers.
7. **When to use**- When k<=nc, b=n  
8. **When not to use**- When very few elements are very large.  

In [60]:
# Radix Sort
def countSort(arr, exp):
    N = len(arr)
    freq = np.zeros(10).astype(int)
    # Get frequency of exp position numbers
    for i in range(N):
        i_digit = int((arr[i]/exp)%10)
        freq[i_digit] += 1
    # Get cummulative frequency
    for i in range(1, 10):
        freq[i] += freq[i-1]
    # sort array
    arr_sorted = np.zeros_like(arr)
    for i in range(N-1,-1,-1):
        i_digit = int((arr[i]/exp)%10)
        arr_sorted[freq[i_digit]-1] = arr[i]        
        freq[i_digit] -= 1
    print(arr_sorted)
        
    return arr_sorted

def radixSort(arr):
    max_value = np.max(arr)
    exp = 1
    while max_value/exp > 1:
        print('exp = ',exp)
        arr = countSort(arr, exp)
        exp *= 10
    return arr
        
arr = np.array(([170, 45, 75, 90, 802, 24, 2, 66]))
print('Array: ', arr)
t=time()
arr_sorted = radixSort(arr)
print('Sorted Array: ',arr_sorted)
print('Time taken = ',time()-t,' sec')

Array:  [170  45  75  90 802  24   2  66]
exp =  1
[170  90 802   2  24  45  75  66]
exp =  10
[802   2  24  45  66 170  75  90]
exp =  100
[  2  24  45  66  75  90 170 802]
Sorted Array:  [  2  24  45  66  75  90 170 802]
Time taken =  0.001865386962890625  sec


## Bucket Sort

1. Radix cant be applied for floating numbers.  
2. Bucket sort used for sorting floating numbers in linear time.  
3. **Complexity**: 
    - Steps 1 and 2 = O(n)  
    - Step 3 = O(n) on average if all numbers are uniformly distributed.  
    - Step 4 = O(n)  
4. **When to use**: mainly useful when input is uniformly distributed over a range.  
5. **When not to use**: High skew in numbers distribution
```
bucketSort(arr[], n)
1) Create n empty buckets (Or lists).
2) Do following for every array element arr[i].
.......a) Insert arr[i] into bucket[n*array[i]]
3) Sort individual buckets using insertion sort.
4) Concatenate all sorted buckets.
```

In [69]:
# Bucket Sort
def insertSort(arr):
    N = len(arr)
    for i in range(1,N):
        key = arr[i]
        j = i-1
        while(j>=0 and key<arr[j]):
            arr[j+1] = arr[j]
            j -= 1
        arr[j+1] = key
    
def bucketSort(arr):
    N = len(arr)
    # Step 1: Create empty buckets
    buckets = [[] for i in range(N)]
    # Step 2: Insert elements into buckets
    for i in range(N):
        bucket_index = int(np.floor(N*arr[i]))
        buckets[bucket_index].append(arr[i])
    print(buckets)
    # Step 3: Sort buckets
    for i in range(N):
        if len(buckets[i])>0:
            insertSort(buckets[i])
    # Step 4: Concatenate buckets
    arr_sorted = []
    for i in range(N):
        arr_sorted += buckets[i]
    return np.array(arr_sorted)
        
arr = np.array(([0.78, 0.17, 0.39, 0.26, 0.72, 0.94, 0.21, 0.12, 0.23, 0.68]))
print('Array: ', arr)
t=time()
arr_sorted = bucketSort(arr)
print('Sorted Array: ',arr_sorted)
print('Time taken = ',time()-t,' sec')

Array:  [0.78 0.17 0.39 0.26 0.72 0.94 0.21 0.12 0.23 0.68]
[[], [0.17, 0.12], [0.26, 0.21, 0.23], [0.39], [], [], [0.68], [0.78, 0.72], [], [0.94]]
Sorted Array:  [0.12 0.17 0.21 0.23 0.26 0.39 0.68 0.72 0.78 0.94]
Time taken =  0.0007402896881103516  sec
